### ISSUE TITLE
is using this build legal? 

### ISSUE THREAD

**Issue by turchinc** [hasalex/eap-build#41]
I was under the impression that EAP releases could not be used in production without a valid support (subscription) agreement - is that (in)correct? Thanks.

**Comment by fcorneli** [comment]
IANAL but AFAIK there are two aspects here:
* eap-build builds "something" based on LGPL licensed source code. You can use LGPL software without any problem as far as you respect the terms of the GNU LGPL license.
* The generated EAP artifact has "JBoss" all over the place, which is a registered trademark of RedHat. Hence you cannot redistribute what comes out of the build process as-is.

So you can use your own builds, but cannot redistribute the thing. At RedHat they are well aware of the fact that it is the branding/trademark law that enables them to enforce certain things. This is also the reason they reserved CentAS.org themselves to prevent a second CentOS scenario. As SaaS vendor I well understand their situation. Positioning good open source software costs money, and it is not more than logical that customers pay for it one way or another: time or money (i.e., via a support contract). If you go the way of eap-build, you will notice that you eventually "pay" in terms of "time". You need to build the thing, maintain it, and if it explodes, solve the issues yourself. So while eap-build might look like a cheap alternative to a JBoss support contract, you have to consider all consequences. If Java EE is not your core business/expertise, going for a JBoss support contract will probably be the better option.

**Comment by eis** [comment]
But to answer to the question, yes, it *should* be legal.

More discussion here:
 - https://developer.jboss.org/thread/197780?start=75&tstart=0
 - https://henk53.wordpress.com/2013/01/09/the-curious-case-of-jboss-as-7-1-2-and-7-1-3/

In jboss.org link Jason Greene (WildFly project lead) commented that there are three ways of using the product, which are

{quote}
1. Stick with community - You get always get the latest and greatest cutting edge stuff (including experimental features), but you have to get support from the community and update more frequently since the community really only focuses on the latest major + minor version.

2. Buy an EAP subscription - You get all of the features above, which lead to minimizing the amount of work you need to spend on app server maintenance and support.

3. Self build and support  EAP - You get some of the benefits of the enterprise releases (e.g. patches to older major versions and so on), but you have to invest time and energy to build and maintain/verify your app server distribution bits.
{quote}

**Comment by turchinc** [comment]
Thank you both for your insightful comments. We are a software company who develop a JEE application that runs on JBoss/EAP/WildFly. We have been using JBoss 7 (and before it JBoss 4) for quite some time and are quite satisfied with quality of the OSS project and the community support. We have actively received assistance and also submitted patches ourselves to the project. And I agree 100%, we have paid for it in terms of "time" now and again :-) 

We are currently reaching out to RedHat regarding subscription, both for our critical internal systems (for these, I suppose we could build and maintain as per point 3) and for customers or potential customers, who may require a more comprehensive SLA (in particular w.r.t. security patches, hardening, etc.).
