### ISSUE TITLE
Is it legal to use the resulting binary in a production environment?

### ISSUE THREAD

**Issue by dcominottim** [hasalex/eap-build#69]
There seems to be no consensus with regard to this subject in forums, etc. For instance, see the following comment from Jason Greene:

"Another topic that was touched on is the licensing terms of the software itself. It is correct that the source code of JBoss EAP is licensed under the LGPL and a combination of other OSS licenses. However the distribution also contains our trademarked images and text which we do not allow redistribution without permission. Anyone that wishes to distribute their own derivative of JBoss EAP needs to replace all occurences of Red Hat and JBoss trademarks, and call it something other than JBoss."

https://developer.jboss.org/message/819862#819862#819862

**Comment by fcorneli** [comment]
You have to make a clear distinction between "use" and "redistribution". Using a home-build JBoss EAP from source yourself is no problem at all as this is governed by the GNU LGPL. In this case, RedHat, as copyright holder, is basically non-existing. As it comes to GNU LGPL, it is the Free Software Foundation that decides on the terms, not RedHat. The software is GNU LGPL licensed, end of story.

However, in the context of a "redistribution" the trademark laws come into picture. Hence you cannot redistribute a JBoss EAP binary without striping the RedHat/JBoss branding.

Notice that RedHat/JBoss branding poses no problem within the context of a home-build JBoss EAP as this (at least according to Belgian law) falls under fair use of the trademarks. E.g., Cola-cola also cannot make any case if you open up a branded can and drink it, since this was supposed to happen (fair use). Same with branded source code: compiling is supposed to happen, hence the branding of a home-build JBoss EAP falls under fair use.

**Comment by fcorneli** [comment]
BTW: this is -at least according to me- why they rebranded to WildFly.

**Comment by eis** [comment]
See also [this issue](https://github.com/hasalex/eap-build/issues/41) where we've discussed this. I don't see how this is not a duplicate.

**Comment by fcorneli** [comment]
Thanks eis for the reminder. I had the feeling that I already made this point somewhere. ;)

**Comment by fcorneli** [comment]
Maybe we should add a paragraph to readme.md about this topic?

**Comment by dcominottim** [comment]
So, let us be more specific: let us suppose that I have a closed-source application that I have sold to a client and that this application is deployed to a homemade JBoss EAP binary that I host on an Amazon EC2 instance. In this case, would I be "using" or "redistributing" the binary?

Additionally, if the above use case is not allowed, I do not see the point or benefit of self-compiling EAP from source, given that Red Hat offers an official binary at $0 cost for development purposes.

**Comment by fcorneli** [comment]
It depends on who exactly is deploying the application server. If you deploy the JBoss EAP that you compiled yourself on your VM/machine, then you "use" it. If however, you pass the compiled JBoss EAP to your client and they deploy it, then you are "redistributing" the JBoss EAP binary.

**Comment by fcorneli** [comment]
Interesting references:
http://twiki.org/cgi-bin/view/Blog/BlogEntry201207x1
https://www.law.washington.edu/lta/swp/law/trademark.html
http://www.iip.or.jp/e/e_summary/pdf/detail2010/e22_15.pdf
